### ISSUE TITLE
Queue() constructor - missing `maxsize` argument.

### ISSUE THREAD

**Issue by folkien** [alex-petrenko/faster-fifo#22]
Not fully compatible with standard Queue. Missing `maxsize` argument.

**Comment by alex-petrenko** [comment]
Indeed this should be implemented. Feel free to submit a PR!

**Comment by alex-petrenko** [comment]
Why not catch the `Full` exception that's raised when there's no more space in the queue?
You can drop a frame every time the exception is raised
